import type {LayoutArkManifest} from "./contracts";
export interface ManifestValidationIssue{path:string;code:string;message:string}
export type ManifestValidationResult={ok:true;value:LayoutArkManifest;issues:[]}|{ok:false;issues:ManifestValidationIssue[]};
const object=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const iso=(v:unknown)=>typeof v==="string"&&Number.isFinite(Date.parse(v))&&/(?:Z|[+-]\\d\\d:\\d\\d)$/.test(v);
const uint=(v:unknown)=>typeof v==="number"&&Number.isSafeInteger(v)&&v>=0;
export function validateManifest(v:unknown):ManifestValidationResult{
 const issues:ManifestValidationIssue[]=[],bad=(path:string,code:string,message:string)=>issues.push({path,code,message});
 if(!object(v))return{ok:false,issues:[{path:"",code:"type",message:"Manifest must be an object"}]};
 const required=(o:Record<string,unknown>,ks:string[],base:string)=>ks.forEach(k=>{if(!(k in o))bad(base?base+"."+k:k,"required","Required property is missing")});
 const exact=(o:Record<string,unknown>,ks:string[],base:string)=>Object.keys(o).forEach(k=>{if(!ks.includes(k))bad(base?base+"."+k:k,"unknown_property","Unknown property")});
 const top=["schema","version","generator","generatedAt","host","roots","scan","files"];required(v,top,"");exact(v,top,"");
 if(v.schema!=="layoutark.manifest")bad("schema","const","Unsupported schema");if(v.version!==1)bad("version","const","Unsupported version");if(!iso(v.generatedAt))bad("generatedAt","date_time","Invalid date-time");
 if(!object(v.generator)||v.generator.name!=="layoutark-scan"||typeof v.generator.version!=="string")bad("generator","shape","Invalid generator");
 if(!object(v.host))bad("host","type","Expected object");else{required(v.host,["psEdition","psVersion","os","hostLabel","publisher"],"host");if(!object(v.host.publisher)||!["yes","no","unknown"].includes(v.host.publisher.detected as string))bad("host.publisher","shape","Invalid Publisher detection")}
 const roots=new Set<number>();if(!Array.isArray(v.roots))bad("roots","type","Expected array");else{if(v.roots.length>32)bad("roots","max_items","Maximum is 32");v.roots.forEach((r,i)=>{if(!object(r)||!uint(r.index)||typeof r.path!=="string"||!["profile","drive","custom"].includes(r.kind as string))bad(`roots[${i}]`,"shape","Invalid root");else if(roots.has(r.index as number))bad(`roots[${i}].index`,"unique","Duplicate root index");else roots.add(r.index as number)})}
 if(!object(v.scan))bad("scan","type","Expected object");else{required(v.scan,["startedAt","finishedAt","complete","fileCount","errors","redaction"],"scan");if(!iso(v.scan.startedAt)||!iso(v.scan.finishedAt)||typeof v.scan.complete!=="boolean"||!uint(v.scan.fileCount)||!Array.isArray(v.scan.errors)||!["profile","names","none"].includes(v.scan.redaction as string))bad("scan","shape","Invalid scan");else v.scan.errors.forEach((e,i)=>{if(!object(e)||typeof e.kind!=="string"||!uint(e.count)||!Array.isArray(e.samples)||e.samples.some(x=>typeof x!=="string"))bad(`scan.errors[${i}]`,"shape","Invalid scan error")})}
 const ids=new Set<string>();if(!Array.isArray(v.files))bad("files","type","Expected array");else{if(v.files.length>500000)bad("files","max_items","Maximum is 500,000");v.files.forEach((f,i)=>{const p=`files[${i}]`;if(!object(f)){bad(p,"type","Expected object");return}required(f,["id","root","relPath","name","sizeBytes","modifiedUtc","createdUtc","cloudState","readOnly","pathLength"],p);if(typeof f.id!=="string"||!f.id)bad(p+".id","type","Invalid id");else if(ids.has(f.id))bad(p+".id","unique","Duplicate id");else ids.add(f.id);if(!uint(f.root)||!roots.has(f.root as number))bad(p+".root","reference","Unknown root");if(typeof f.relPath!=="string"||typeof f.name!=="string"||!f.name||!uint(f.sizeBytes)||!uint(f.pathLength)||!iso(f.modifiedUtc)||!iso(f.createdUtc)||!["local","placeholder","unknown"].includes(f.cloudState as string)||typeof f.readOnly!=="boolean")bad(p,"shape","Invalid file")});if(object(v.scan)&&uint(v.scan.fileCount)&&v.scan.fileCount!==v.files.length)bad("scan.fileCount","consistency","Does not match files.length")}
 return issues.length?{ok:false,issues}:{ok:true,value:v as unknown as LayoutArkManifest,issues:[]};
}
export function parseManifest(json:string):ManifestValidationResult{try{return validateManifest(JSON.parse(json))}catch{return{ok:false,issues:[{path:"",code:"json",message:"Invalid JSON"}]}}}
